# Generated by Django 5.2.4 on 2025-08-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_clientprofile_telegram_and_more'),
        ('booking', '0001_initial'),
        ('showcase', '0011_alter_specialist_order_alter_specialist_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.serviceprice', verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('specialist', 'service', 'date', 'start_time')},
        ),
    ]
