# Generated by Django 5.2.4 on 2025-08-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_clientprofile_telegram_and_more'),
        ('booking', '0002_alter_availability_unique_together_and_more'),
        ('showcase', '0012_specialist_services'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('specialist', 'date', 'start_time')},
        ),
        migrations.AlterField(
            model_name='availability',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.serviceprice', verbose_name='Услуга'),
        ),
    ]
