# Generated by Django 5.2.4 on 2025-08-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_bookable',
            field=models.BooleanField(default=True, verbose_name='Слот доступен для записи'),
        ),
    ]
