# Generated by Django 5.2.4 on 2025-08-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_availability_is_bookable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='is_bookable',
        ),
    ]
