# Generated by Django 5.2.4 on 2025-08-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hair', 'Уход за волосами'), ('nails', 'Ногтевой сервис'), ('cosmetology', 'Косметология'), ('makeup', 'Макияж'), ('brows_lashes', 'Уход за бровями и ресницами'), ('epilation', 'Эпиляция и депиляция'), ('body', 'Массаж и уход за телом'), ('tattoo_piercing', 'Тату и пирсинг'), ('styling', 'Стилистика и имидж'), ('kids', 'Детская бьюти-сфера'), ('alternative', 'Альтернативные направления'), ('education', 'Обучение и менторство')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=100, verbose_name='Название мастерской')),
                ('workshop_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон мастерской')),
                ('activity_area', models.ManyToManyField(to='accounts.activityarea', verbose_name='Сферы деятельности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
