# Generated by Django 5.2.4 on 2025-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='activity_area',
            field=models.CharField(choices=[('phones', 'Ремонт телефонов'), ('computers', 'Ремонт компьютеров'), ('both', 'Ремонт телефонов и компьютеров'), ('appliances', 'Ремонт бытовой техники'), ('car_repair', 'Ремонт авто'), ('car_paint', 'Покраска авто')], default='phones', max_length=30, verbose_name='Сфера деятельности'),
        ),
    ]
