# Generated by Django 5.2.4 on 2025-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_populate_activity_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityarea',
            options={'verbose_name': 'Сфера деятельности', 'verbose_name_plural': 'Сферы деятельности'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='workshopprofile',
            options={'verbose_name': 'Профиль бьюти-студии', 'verbose_name_plural': 'Профили бьюти-студий'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='category',
            field=models.CharField(choices=[('hair', 'Уход за волосами'), ('nails', 'Ногтевой сервис'), ('cosmetology', 'Косметология'), ('makeup', 'Макияж'), ('brows_lashes', 'Уход за бровями и ресницами'), ('epilation', 'Эпиляция и депиляция'), ('body', 'Массаж и уход за телом'), ('tattoo_piercing', 'Тату и пирсинг'), ('styling', 'Стилистика и имидж'), ('kids', 'Детская бьюти-сфера'), ('alternative', 'Альтернативные направления'), ('education', 'Обучение и менторство')], max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='activityarea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон бьюти-студии'),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='workshop_name',
            field=models.CharField(max_length=100, verbose_name='Название бьюти-студии'),
        ),
    ]
