# Generated by Django 5.2.4 on 2025-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activityarea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы'),
        ),
    ]
