# Generated by Django 5.2.4 on 2025-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_workshopprofile_activity_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='workshopprofile',
            name='activity_area',
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='activity_area',
            field=models.ManyToManyField(to='accounts.activityarea', verbose_name='Сферы деятельности'),
        ),
    ]
