# Generated by Django 5.2.4 on 2025-08-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workshopprofile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Длительность')),
                ('activity_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.activityarea', verbose_name='Сфера деятельности')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='accounts.workshopprofile')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'Цены услуг',
            },
        ),
    ]
