# Generated by Django 5.2.4 on 2025-08-14 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_serviceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='duration',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{2}:\\d{2}$', 'Формат времени должен быть ЧЧ:ММ')], verbose_name='Длительность'),
        ),
    ]
