# Generated by Django 5.2.4 on 2025-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_serviceprice_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность'),
        ),
    ]
