# Generated by Django 5.2.4 on 2025-08-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='viber',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='workshopprofile',
            name='viber',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viber'),
        ),
    ]
