# Generated by Django 5.2.4 on 2025-08-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientprofile_telegram_clientprofile_viber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='viber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='workshopprofile',
            name='viber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Viber'),
        ),
    ]
