# Generated by Django 5.2.4 on 2025-08-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_clientprofile_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='viber',
        ),
        migrations.RemoveField(
            model_name='workshopprofile',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='workshopprofile',
            name='viber',
        ),
    ]
