# Generated by Django 5.2.4 on 2025-08-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_activityarea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='showcase/covers/', verbose_name='Фото главной страницы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='showcase', to='accounts.workshopprofile')),
            ],
            options={
                'verbose_name': 'Витрина',
                'verbose_name_plural': 'Витрины',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showcase/gallery/', verbose_name='Изображение работы')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='showcase.showcase')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
    ]
