# Generated by Django 5.2.4 on 2025-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_galleryimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
