# Generated by Django 5.2.4 on 2025-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_galleryimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instagram (имя или ссылка)'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telegram (имя или ссылка)'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='viber',
            field=models.CharField(blank=True, max_length=30, verbose_name='Viber (номер)'),
        ),
    ]
