# Generated by Django 5.2.4 on 2025-08-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_showcase_instagram_showcase_telegram_showcase_viber'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание витрины'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон витрины'),
        ),
        migrations.AddField(
            model_name='showcase',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы витрины'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='viber',
            field=models.CharField(blank=True, max_length=255, verbose_name='Viber'),
        ),
    ]
