# Generated by Django 5.2.4 on 2025-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_showcase_description_showcase_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='showcase',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='showcase',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='showcase',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='showcase',
            name='viber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Viber'),
        ),
    ]
