# Generated by Django 5.2.4 on 2025-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_remove_showcase_description_remove_showcase_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcase',
            name='instagram',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Instagram (username или ссылка)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcase',
            name='telegram',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Telegram (username или ссылка)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcase',
            name='viber',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Viber (номер или ссылка)'),
            preserve_default=False,
        ),
    ]
