# Generated by Django 5.2.4 on 2025-08-22 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_alter_showcase_instagram_alter_showcase_telegram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='showcase/specialists/', verbose_name='Фото специалиста')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, verbose_name='О специалисте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на витрине')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок (меньше — выше)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='showcase.showcase')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'ordering': ['order', 'last_name', 'first_name'],
            },
        ),
    ]
