# Generated by Django 5.2.4 on 2025-08-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0009_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
