# Generated by Django 5.2.4 on 2025-08-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_alter_specialist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок (меньше — выше)'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='showcase/specialists/', verbose_name='Фото'),
        ),
    ]
