# Generated by Django 5.2.4 on 2025-08-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_clientprofile_telegram_and_more'),
        ('showcase', '0011_alter_specialist_order_alter_specialist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='accounts.serviceprice', verbose_name='Услуги'),
        ),
    ]
