# Generated by Django 5.2.4 on 2025-08-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_clientprofile_telegram_and_more'),
        ('showcase', '0012_specialist_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='specialists', to='accounts.serviceprice', verbose_name='Услуги, которые выполняет специалист'),
        ),
    ]
